### ISSUE TITLE
Allow DateTime Axis

### ISSUE THREAD

**Issue by yvesmauron** [yvesmauron/bt#16]
- [ ] Allow DateTime or Time on X Axis
- [ ] Allow dynamic labels based on zoom on X Axis
- [ ] Allow custom axis labels based on zoom level

**Comment by yvesmauron** [comment]
Also allow for single trace plots to increase performance for large data.

Everything should be callable via one function and default to the logical option.

**Comment by yvesmauron** [comment]
- [x] Allow DateTime or Time on X Axis
- [x] Allow dynamic labels based on zoom on X Axis
- [x] Allow custom axis labels based on zoom level

**Comment by zackarno** [comment]
Hi @yvesmauron  - this looks like a package that could be very useful. While I see this issue has been resolved- it is not clear how this functionality works. When I plot a date on the x-axis  the resulting graph is zoomed way out and I have to double click on it to zoom in on any actual data. It would be nice if there was a way that the plot could be fit to the data. Also it would be nice if we could disable all range sliders and just have a plot of the full data.

See reprex below:

``` r
library(tidyverse)
library(catmaply)


# create some fake data
dataset <- tibble(
  # will show example using date in both formates (date, dt below)
  date = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
  numeric_fill = sample(1000:2000, size = 32),
  categoric_fill = sample(1:5, size = 32,replace=T),
  numeric_x = sample(c(1:8), size = 32,replace = T),
  categoric_y = sample(LETTERS[1:5],32, replace = T),
  
)


catmaply(
  dataset ,
  x=date,
  y=categoric_y,
  z= categoric_fill
)
```

![](https://i.imgur.com/eyYUPNR.png)

<sup>Created on 2022-10-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by christophbaur** [comment]
Hi @zackarno!

You can deactivate the rangeslider quite simple with `rangeslider=FALSE` and fix the zoom Issue with `xaxis=list(autorange=TRUE) ` within the plotly layout options.

This one will work:

```R
library(tidyverse)
library(catmaply)
library(plotly)

# create some fake data
dataset <- tibble(
  # will show example using date in both formates (date, dt below)
  date = seq(as.Date("2017-01-01", tz='UTC'), as.Date("2017-02-01", tz='UTC'), by = 1),
  numeric_fill = sample(1000:2000, size = 32),
  categoric_fill = sample(1:5, size = 32,replace=T),
  numeric_x = sample(c(1:8), size = 32,replace = T),
  categoric_y = sample(LETTERS[1:5],32, replace = T),
  
)

catmaply(
  dataset ,
  x=date,
  y=categoric_y,
  z= categoric_fill,
  rangeslider = FALSE
)%>%
  layout(xaxis = list(autorange = TRUE)
         )
```

![image](https://user-images.githubusercontent.com/69149103/198113367-8763815c-63ce-4457-ba57-eaa07339a194.png)


Nevertheless  as.date()-values does not behave as I would expect as well. If you transform them in a POSIXct-value it works as expected without the additional codelines above. 
 
@yvesmauron: I will reopen this isse and may you have a look at it in the next few days? Thank you

Regards Chris

**Comment by yvesmauron** [comment]
Hi @zackarno

Thanks for your interest in the package. At the moment, only POSIXct / POSIXt are supported for the dynamic time axis; but we can easily extend this to allow `Date` as well. 

I would propose the following changes in regard to default behaviour:

If `Date` is submitted, it will - by default - use a dynamic x-axis that adjusts its labels based on zoom level.
```{R}
library(tidyverse)
library(catmaply)
library(plotly)

# create some fake data
dataset <- tibble(
  # will show example using date in both formates (date, dt below)
  date = seq(as.Date("2017-01-01", tz='UTC'), as.Date("2017-02-01", tz='UTC'), by = 1),
  numeric_fill = sample(1000:2000, size = 32),
  categoric_fill = sample(1:5, size = 32,replace=T),
  numeric_x = sample(c(1:8), size = 32,replace = T),
  categoric_y = sample(LETTERS[1:5],32, replace = T),

)

catmaply(
  dataset ,
  x=date,
  y=categoric_y,
  z= categoric_fill,
  rangeslider = FALSE
)
```
![image](https://user-images.githubusercontent.com/56515535/209435310-bd17559e-12b9-43e5-b607-d94d938f87e9.png)

If dates are formatted as char, then they are regarded normally as "categorical" x-axis.
```{R}
string_dates = c()
for (d in seq.int(length.out = 32)) {
  string_dates <- append(string_dates, format(dataset[["date"]][[d]], "%Y-%b-%d"))
}
dataset[["date"]] <- string_dates

catmaply(
  dataset ,
  x=date,
  y=categoric_y,
  z= categoric_fill,
  rangeslider = FALSE
)
```
![image](https://user-images.githubusercontent.com/56515535/209435379-188929cd-4589-4922-82de-f4c7ce3ec9c0.png)


If dates are formatted as  POSIXct / POSIXt, then the behavior is the same currently and es defined in the initial requirements, meaning a dynamic x-axis optimized for daily/summarized data. 

```{R}
string_dates = c()
data("vbz")
df <- na.omit(vbz[[1]])
df <- df %>%
  na.omit() %>%
  dplyr::group_by(
    trip_seq
  ) %>%
  dplyr::mutate(
    departure_date_time = min(na.omit(lubridate::ymd_hms(paste("2020-08-01", departure_time))))
  ) %>%
  dplyr::ungroup()

catmaply(
  df,
  x=departure_date_time,
  y = stop_name,
  y_order = stop_seq,
  z = occupancy,
  categorical_color_range = TRUE,
  categorical_col = occ_category,
  color_palette = viridis::inferno,
  hover_template = paste(
    '<br><b>Trip</b>:', trip_seq,
    '<br><b>Stop Name</b>:', stop_name,
    '<br><b>Occupancy category</b>:', occ_cat_name,
    '<br><b>Occupancy</b>:', round(occupancy, 2),
    '<extra></extra>'
  )
)
```
![image](https://user-images.githubusercontent.com/56515535/209435383-62e42f09-26dc-43ab-98a6-40ec96963d96.png)

Note that you can still overwrite default tickformatstops in catmaply as usual in [plotly](https://plotly.com/r/time-series/) for `Date` or POSIXct / POSIXt: see e.g.

```{R}
catmaply(
  df,
  x=departure_date_time,
  y = stop_name,
  y_order = stop_seq,
  z = occupancy,
  categorical_color_range = TRUE,
  categorical_col = occ_category,
  color_palette = viridis::inferno,
  hover_template = paste(
    '<br><b>Trip</b>:', trip_seq,
    '<br><b>Stop Name</b>:', stop_name,
    '<br><b>Occupancy category</b>:', occ_cat_name,
    '<br><b>Occupancy</b>:', round(occupancy, 2),
    '<extra></extra>'
  ),
  tickformatstops=list(
    list(dtickrange = list(NULL, 1000), value = "%H:%M:%S.%L"),
    list(dtickrange = list(1000, 60000), value = "%H:%M:%S"),
    list(dtickrange = list(60000, 3600000), value = "%H:%M"),
    list(dtickrange = list(3600000, 86400000), value = "%H:%M"),
    list(dtickrange = list(86400000, 604800000), value = "%H:%M"),
    list(dtickrange = list(604800000, "M1"), value = "%H:%M"),
    list(dtickrange = list("M1", "M12"), value = "%H:%M"),
    list(dtickrange = list("M12", NULL), value = "%H:%M")
  )
)
```
![image](https://user-images.githubusercontent.com/56515535/209435862-0b5f7a1f-2b11-4a82-8a24-d3b7bc615e0a.png)

@christophbaur and @zackarno : what do you think regarding this adjustment to the default behavior?

**Comment by christophbaur** [comment]
Thanks @yvesmauron! Sounds like a very good enhancement. In my opinion there's no reason not to do this.
